# Generated by Django 3.2.5 on 2021-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carbos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='kcal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.IntegerField(default=1),
        ),
    ]
